version: "3.9"
services:

  ### Prefect Database
  database:
    container_name: "prefect_flow_database"
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ### Prefect Server API and UI
  server:
    build:
          context: .
          dockerfile: Dockerfile
    volumes:
      - ./flows:/opt/prefect/flows
    environment:
      - TZ=Asia/Bangkok
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database

volumes:
  prefect:
  db:
networks:
  default:
    name: prefect-network